// Wave 1: the Anti-hero's key strikes (docs/combat/pending/wave1-strikes.md, strikes.antihero.wave1.json) as pose sketches.
// Authored by Animation: one contact pose per strike (or a derivation from a base family with overrides); the chamber and the
// follow-through come from wave_gen.mjs (a per-limb chamber template and a blend of the contact toward the guard). Originality: no
// franchise pose; each pose gets its _orig line from `orig` here. Hands are open blades or claws unless the look says a fist.
const LUNGE = { foot_r: [-6, 2.5, 9], foot_l: [26, 2.5, -7] };
const LUNGE_S = { foot_r: [-6, 2.5, 9], foot_l: [20, 2.5, -7] };
const OPEN = { hands: { r: 'open', l: 'open' } };
const CLAW = { hands: { r: 'claw', l: 'claw' } };

export const strikes = {
  // ---- one arm, derived from a base family
  jab: { from: 'jab', over: { all: { ...OPEN } }, kind: 'hand',
    orig: 'a straight blade hand from the lead shoulder, the arm one line with the rear leg, the body barely turning' },
  cross: { from: 'cross', over: { all: { ...OPEN }, contact: { hand_l: [10, 50, -4] }, follow: { hand_l: [10, 50, -4] } }, kind: 'hand',
    orig: 'the rear blade hand driven through the chest with the hips turned full, the lead forearm folded across the ribs' },
  hook: { from: 'hook', over: { all: { ...OPEN } }, kind: 'hand',
    orig: 'a flat tight arc at head height, the elbow a sharp right angle, the plated forearm leading the hand' },
  backfist: { from: 'hook', kind: 'hand', family: 'hand_arc', genericAb: true,
    contact: { family: 'upright_lunge', lean: 14, hips: [18, -3, 0], spine: { lean: -2, twist: -30 }, head: { pitch: 2, yaw: -12 },
      hand_r: [50, 72, 12], pole_hand_r: [2, 8, 10], hand_l: [12, 58, -8], ...LUNGE, ...OPEN },
    orig: 'the arm unfolding backhanded to full length, the back of the hand leading, the chest opened away from the rival' },
  palm_heel: { from: 'jab', over: { all: { ...CLAW } }, kind: 'hand', legal: ['hands_open_or_claw', 'not_at_hip'],
    orig: 'a clawed open palm pushed straight in from the ribs, fingers spread like tines, the wrist bent back' },
  spear_hand: { from: 'cross', kind: 'hand',
    over: { all: { ...OPEN }, contact: { family: 'crouched', lean: 26, hips: [14, -12, 0], spine: { lean: 8, twist: 30 }, hand_r: [50, 46, 6], hand_l: [8, 50, -4] },
      follow: { hand_r: [38, 46, 8] } },
    orig: 'a low blade-hand thrust from the crouch into the gut, the spine and the arm one long diagonal' },
  uppercut: { from: 'upper', kind: 'hand', legal: ['no_leap', 'no_held_raise'],
    over: { all: { hands: { r: 'fist', l: 'open' } }, follow: { hand_r: [34, 72, 8] } },
    alt: { label: 'upright and open-chested', contact: { lean: 4, hips: [16, -2, 0], spine: { lean: -10, twist: 20 }, head: { pitch: -14 }, hand_r: [50, 84, 8] } },
    orig: 'a closed fist rising under the chin, the rise in the hip and shoulder, the feet planted, the other arm low across the body' },
  hammer: { kind: 'hand', chamber: { lean: -6, hips: [-3, -2, 0], spine: { lean: -10, twist: -8 }, head: { pitch: -8 }, hand_r: [4, 92, 9], pole_hand_r: [-8, 2, 8] },
    contact: { family: 'upright_lunge', lean: 26, hips: [16, -5, 0], spine: { lean: 16, twist: 14 }, head: { pitch: 20, yaw: 2 },
      hand_r: [42, 74, 6], pole_hand_r: [-6, 12, 8], hand_l: [16, 56, -8], ...LUNGE, hands: { r: 'fist', l: 'open' } },
    orig: 'the fist brought straight down from above the head like a dropped blade, the body folding over it' },
  overhand: { from: 'hook', kind: 'hand', family: 'hand_arc', chamber: { hand_r: [2, 62, 22], pole_hand_r: [-8, 0, 12] },
    contact: { family: 'upright_lunge', lean: 28, hips: [20, -6, 0], spine: { lean: 10, twist: 40 }, head: { pitch: 18, yaw: -4 },
      hand_r: [52, 76, 10], pole_hand_r: [-2, 12, 6], hand_l: [14, 56, -8], ...LUNGE, ...OPEN },
    orig: 'a looping blow over the rival guard, the shoulder rolled high, the head ducked off the line' },
  haymaker: { from: 'hook', kind: 'hand',
    over: { all: { ...OPEN }, chamber: { hand_r: [-8, 60, 26], pole_hand_r: [-8, -2, 14], spine: { twist: -38 } },
      contact: { hand_r: [50, 66, 26], pole_hand_r: [2, -2, 14], spine: { twist: 52, lean: 6, bend: -8 }, lean: 22 } },
    orig: 'the widest swing he has: the arm nearly straight, the whole torso thrown round behind it' },

  // ---- elbows (aim-only limb; the head blows land on the jaw socket)
  short_elbow: { kind: 'elbow', target: 'jaw', step_max: 16,
    contact: { family: 'upright_lunge', lean: 8, hips: [5, -2, 0], spine: { lean: 4, twist: 36 }, head: { pitch: 6, yaw: 2 },
      hand_r: [14, 68, 6], pole_hand_r: [12, 2, 4], hand_l: [12, 56, -8], foot_r: [-8, 2.5, 9], foot_l: [12, 2.5, -7], ...OPEN },
    orig: 'the forearm folded shut and the point of the elbow cut across at face height: a small sharp triangle' },
  rising_elbow: { kind: 'elbow', target: 'jaw', step_max: 16,
    chamber: { family: 'crouched', lean: 10, hips: [0, -8, 0], spine: { lean: 6, twist: -10 }, hand_r: [10, 44, 12], pole_hand_r: [-8, -4, 10], hand_l: [22, 56, -8] },
    contact: { family: 'upright', lean: 6, hips: [6, 2, 0], spine: { lean: -8, twist: 20 }, head: { pitch: -6, yaw: 4 },
      hand_r: [0, 82, 4], pole_hand_r: [12, 4, 2], hand_l: [12, 56, -8], foot_r: [-6, 2.5, 9], foot_l: [12, 2.5, -7], ...OPEN },
    orig: 'the elbow driven up the centre line, the hand ending behind his own ear, the plate edge leading' },
  spinning_elbow: { kind: 'elbow', target: 'jaw', step_max: 16, legal: ['single_turn'],
    chamber: { hip_twist: -24, spine: { lean: 4, twist: -50 } },
    contact: { family: 'upright_lunge', lean: 10, hip_twist: 40, hips: [8, -2, 0], spine: { lean: 2, twist: 60 }, head: { pitch: 4, yaw: -30 },
      hand_r: [26, 66, 12], pole_hand_r: [6, 2, 10], hand_l: [-8, 58, -14], foot_r: [-6, 2.5, 9], foot_l: [10, 2.5, -7], ...OPEN },
    orig: 'one turn with his back shown, the elbow whipping through level at the end of it' },
  dropping_elbow: { kind: 'elbow', target: 'chest', step_max: 16,
    chamber: { hand_r: [8, 84, 8], pole_hand_r: [-4, 16, 6], lean: 6, hips: [-2, -2, 0], spine: { lean: -4, twist: -16 } },
    contact: { family: 'upright_lunge', lean: 18, hips: [6, -8, 0], spine: { lean: 12, twist: 20 }, head: { pitch: 16 },
      hand_r: [18, 64, 6], pole_hand_r: [12, -6, 4], hand_l: [32, 60, -10], foot_r: [-8, 2.5, 9], foot_l: [12, 2.5, -7], ...OPEN },
    orig: 'the point of the elbow dropped onto the chest from above, the other hand pinning the rival guard down' },

  // ---- two arms
  twin_spear: { kind: 'two_hand', chamber: { lean: 8, hand_r: [4, 50, 6], hand_l: [4, 50, -6] },
    contact: { family: 'upright_lunge', lean: 22, hips: [20, -6, 0], spine: { lean: 6, twist: 0 }, head: { pitch: 8 },
      hand_r: [60, 52, 5], hand_l: [60, 52, -5], ...LUNGE, ...OPEN },
    orig: 'both blade hands thrust side by side, a hand apart, the elbows locked: two parallel lines' },
  double_palm: { kind: 'two_hand', chamber: { lean: 4, hand_r: [10, 62, 16], pole_hand_r: [-8, 0, 18], hand_l: [10, 62, -16], pole_hand_l: [-8, 0, -18] }, legal: ['wrists_apart', 'hands_open_or_claw', 'not_at_hip'], follow_t: 0.7,
    contact: { family: 'upright_lunge', lean: 20, hips: [18, -4, 0], spine: { lean: 4 }, head: { pitch: 6 },
      hand_r: [56, 64, 13], pole_hand_r: [-2, 0, 16], hand_l: [56, 64, -13], pole_hand_l: [-2, 0, -16], ...LUNGE, ...CLAW },
    alt: { label: 'elbows in', contact: { hand_r: [56, 64, 9], hand_l: [56, 64, -9], pole_hand_r: [-2, 0, 6], pole_hand_l: [-2, 0, -6] } },
    orig: 'both clawed palms shoved in at shoulder width, fingers up, the elbows flared wide' },
  double_hammer: { kind: 'two_hand', legal: ['wrists_apart', 'no_clasp'],
    chamber: { lean: -4, hips: [-2, -2, 0], hand_r: [6, 98, 11], pole_hand_r: [-8, 4, 8], hand_l: [6, 98, -11], pole_hand_l: [-8, 4, -8] },   // RL-105: the hands at the peak a shoulder width apart (22 drawn; Legal asks 20)
    contact: { family: 'upright_lunge', lean: 26, hips: [16, -6, 0], spine: { lean: 16 }, head: { pitch: 18 },
      hand_r: [38, 64, 8], pole_hand_r: [-8, 14, 10], hand_l: [38, 64, -8], pole_hand_l: [-8, 14, -10], ...LUNGE, ...OPEN },
    orig: 'both forearm guards brought down side by side like a dropped bar, the hands apart and open' },
  cross_arm_ram: { kind: 'two_hand', target: 'chest', chamber: { lean: 4, spine: { twist: -10 }, hand_r: [4, 62, 16], hand_l: [4, 60, -14] }, step_max: 16, legal: ['no_cross_hold'],
    follow: { hand_r: [14, 58, 10], hand_l: [14, 56, -8] },
    contact: { family: 'upright_lunge', lean: 16, hips: [6, -4, 0], spine: { lean: 10 }, head: { pitch: 24 },
      hand_r: [24, 66, -8], pole_hand_r: [8, -2, -10], hand_l: [24, 64, 8], pole_hand_l: [8, -2, 10], foot_r: [-8, 2.5, 9], foot_l: [12, 2.5, -7], ...OPEN },
    orig: 'the forearm guards crossed into a wedge and driven in behind the shoulders, the head tucked behind the plates' },

  // ---- feet
  front_kick: { from: 'kick', over: { all: { ...OPEN } }, kind: 'foot',
    orig: 'a straight push with the ball of the foot from a high knee, the body leaning back off the line' },
  side_kick: { kind: 'foot',
    chamber: { spine: { lean: -4, twist: -24 } },
    contact: { family: 'upright_lunge', lean: -28, hips: [14, -2, 0], spine: { lean: -10, twist: -44 }, head: { pitch: 0, yaw: 24 },
      hand_r: [16, 58, 12], hand_l: [-26, 54, -10], foot_r: [50, 46, 8], foot_l: [8, 2.5, -7], ...OPEN },
    orig: 'turned fully side-on, the leg and the opposite arm one horizontal line, the heel leading' },
  low_kick: { from: 'round', kind: 'foot',
    over: { all: { ...OPEN }, chamber: { foot_r: [4, 22, 16] },
      contact: { lean: 4, hips: [14, -2, 0], spine: { lean: 2, twist: 14 }, foot_r: [44, 20, 8], hand_r: [6, 58, 14], hand_l: [20, 60, -10], foot_l: [14, 2.5, -7] },
      follow: { foot_r: [20, 18, 9] } },
    orig: 'a short chop of the shin into the thigh, his own body upright and still' },
  snap_round: { from: 'round', kind: 'foot',
    over: { all: { ...OPEN }, chamber: { foot_r: [12, 40, 10] },
      contact: { lean: -6, spine: { lean: -4, twist: 12 }, foot_r: [44, 50, 8], hips: [16, -2, 0] }, follow: { foot_r: [14, 38, 8] } },
    orig: 'a quick whip from the knee, the hips barely turned, the foot back before the rival moves' },
  roundhouse: { from: 'round', kind: 'foot',
    over: { all: { ...OPEN }, contact: { hand_l: [-14, 60, -10], hand_r: [-2, 54, 16] }, follow: { hand_l: [-4, 58, -10] } },
    alt: { label: 'guard stays up', contact: { hand_l: [18, 66, -10], hand_r: [10, 62, 14] }, follow: { hand_l: [18, 62, -8] } },
    orig: 'the full turn of the hips, the leg a long blade through the ribs, the arms thrown back the other way' },
  axe_kick: { kind: 'foot', step_max: 12,
    chamber: { lean: -10, hips: [-2, 0, 0], spine: { lean: -8 }, foot_r: [6, 66, 8], hand_r: [-4, 56, 18], hand_l: [4, 60, -16] },
    contact: { family: 'upright_lunge', lean: -2, hips: [8, 0, 0], spine: { lean: -8 }, head: { pitch: 4 },
      hand_r: [-4, 56, 18], hand_l: [4, 60, -16], foot_r: [30, 58, 6], foot_l: [10, 2.5, -7], ...OPEN },
    alt: { label: 'leaning back, arms wide', contact: { lean: -14, spine: { lean: -14 }, hand_r: [-16, 64, 22], hand_l: [-6, 70, -20] } },
    orig: 'the leg lifted straight and brought down heel first onto the collar, his body a vertical line beside it' },
  spinning_heel: { kind: 'foot', legal: ['single_turn'],
    chamber: { hip_twist: -30, spine: { twist: -40, lean: -4 }, foot_r: [-4, 30, 10] },
    contact: { family: 'upright_lunge', lean: -10, hip_twist: 70, hips: [8, 0, 0], spine: { lean: -4, twist: 60 }, head: { yaw: -40 },
      hand_r: [-10, 60, 16], hand_l: [10, 60, -16], foot_r: [38, 50, 8], foot_l: [6, 2.5, -7], ...OPEN },
    orig: 'one turn with his back shown, the heel coming round at the end of a straight leg' },
  stomp: { kind: 'foot',
    chamber: { foot_r: [16, 48, 8], pole_foot_r: [10, 6, 0], hand_r: [8, 62, 22], hand_l: [8, 62, -22] },
    contact: { family: 'upright_lunge', lean: 6, hips: [12, 0, 0], spine: { lean: 0 }, head: { pitch: 10 },
      hand_r: [8, 62, 22], hand_l: [8, 62, -22], foot_r: [32, 38, 8], pole_foot_r: [10, 6, 0], foot_l: [12, 2.5, -7], ...OPEN },
    orig: 'the knee drawn to his chest and the sole driven straight down, his arms spread for balance' },
  sweep: { kind: 'foot', target: 'shins', step_max: 18,
    chamber: { family: 'crouched', lean: 20, hips: [0, -20, 0], spine: { lean: 12 }, hand_l: [20, 8, -10], hand_r: [4, 44, 12], foot_r: [-6, 4, 9], foot_l: [4, 2.5, -8] },
    contact: { family: 'crouched', lean: 36, hips: [4, -26, 0], spine: { lean: 22 }, head: { pitch: 14 },
      hand_l: [26, 4, -10], hand_r: [2, 44, 12], foot_r: [36, 6, 8], foot_l: [-2, 3, -8], ...OPEN },
    orig: 'dropped onto one hand, the other leg scything flat along the ground' },
  drop_kick: { kind: 'foot', limb2: 'foot_l',
    chamber: { lean: -30, hips: [-4, 4, 0], foot_r: [20, 40, 4], foot_l: [20, 38, -4], hand_r: [-10, 40, 12], hand_l: [-10, 40, -12] },
    contact: { family: 'airborne_neutral', lean: -70, hips: [0, 6, 0], spine: { lean: -10 }, head: { pitch: -20 },
      hand_r: [-26, 34, 12], hand_l: [-26, 34, -12], foot_r: [34, 50, 4], foot_l: [34, 48, -4], ...OPEN },
    orig: 'both feet together with the body laid flat behind them, the arms back along his sides' },

  // ---- knees, head, torso
  short_knee: { kind: 'knee', target: 'gut', step_max: 16, chamber: { hand_r: [12, 52, 12], hand_l: [28, 64, -8], foot_r: [2, 26, 8] },
    contact: { family: 'upright_lunge', lean: -6, hips: [4, -2, 0], spine: { lean: -2, twist: 8 }, head: { pitch: 6 },
      hand_r: [22, 52, 12], hand_l: [30, 66, -8], foot_r: [20, 22, 8], pole_foot_r: [10, 1, 0], foot_l: [6, 2.5, -7], ...OPEN },
    orig: 'a short knee from the clinch, one hand on the rival shoulder, the standing leg straight' },
  rising_knee: { kind: 'knee', target: 'gut', step_max: 16, chamber: { lean: 6, hips: [0, -6, 0], hand_r: [14, 70, 10], hand_l: [14, 70, -10], foot_r: [-2, 4, 8] },
    contact: { family: 'upright_lunge', lean: -8, hips: [4, 4, 0], spine: { lean: -4 }, head: { pitch: -4 },
      hand_r: [22, 48, 10], hand_l: [22, 48, -10], foot_r: [24, 28, 8], pole_foot_r: [10, 1, 0], foot_l: [6, 5, -7], ...OPEN },
    orig: 'the knee driven up as he rises onto the toes, the hips thrust through, both hands pulling down' },
  driving_knee: { kind: 'knee', target: 'gut', step_max: 16, chamber: { lean: 8, hips: [-4, -2, 0], hand_r: [24, 56, 10], hand_l: [-2, 54, -10], foot_r: [-12, 8, 8], foot_l: [10, 2.5, -7] },
    contact: { family: 'upright_lunge', lean: -14, hips: [8, -2, 0], spine: { lean: -6 }, head: { pitch: 0 },
      hand_r: [18, 52, 12], hand_l: [20, 54, -10], foot_r: [26, 26, 8], pole_foot_r: [10, 1, 0], foot_l: [-12, 6, -7], ...OPEN },
    orig: 'a knee carried in on the end of a run, the body leaning back, the trailing leg straight behind' },
  headbutt: { kind: 'head', target: 'jaw', step_max: 16,
    contact: { family: 'upright_lunge', lean: 18, hips: [6, -6, 0], spine: { lean: 14 }, head: { pitch: 26, yaw: 2 },
      hand_r: [22, 52, 12], hand_l: [22, 52, -12], foot_r: [-10, 2.5, 9], foot_l: [4, 2.5, -7], ...OPEN },
    alt: { label: 'hands pulled back', contact: { hand_r: [-6, 48, 12], hand_l: [-6, 48, -12] } },
    orig: 'the masked brow snapped forward from the neck and waist, the hands holding the rival arms down' },
  shoulder_check: { kind: 'shoulder', target: 'chest', step_max: 16,
    contact: { family: 'upright_lunge', lean: 16, hips: [6, -4, 0], spine: { lean: 8, twist: 40 }, head: { pitch: 14, yaw: 24 },
      hand_r: [14, 54, 8], hand_l: [12, 52, -8], foot_r: [-8, 2.5, 9], foot_l: [12, 2.5, -7], ...OPEN },
    orig: 'a short step and the plated shoulder into the chest, the chin tucked behind it, the arms close' },
  body_ram: { kind: 'shoulder', target: 'chest', step_max: 16,
    chamber: { lean: 6, hips: [-3, -4, 0], hip_twist: -24, spine: { twist: -30 }, head: { yaw: 20 } },
    contact: { family: 'airborne_neutral', lean: 14, hip_twist: 96, hips: [4, 10, 0], spine: { lean: 6, twist: 62 }, head: { pitch: 10, yaw: -70 },
      hand_r: [6, 58, 18], hand_l: [0, 56, -14], foot_r: [-6, 18, 9], foot_l: [8, 14, -7], ...OPEN },
    orig: 'he turns as he arrives and throws the plated back and the back of the shoulder into the chest, the head turned away over the far shoulder, both feet leaving the ground' },
};
