extends SceneTree
## Held-pose lint CLI (the rules and the scope are in render/anim/anim_held_lint.gd; Legal RL-087). `--strict` exits 1 on any failure or a missing scope; anim_check runs the same scan as a gate.
##   godot --headless --path . -s res://render/anim/tools/held_scan.gd -- [--md=docs/animation/held-lint.md] [--json=out.json] [--strict] [--list]
var md_out: String = ""
var json_out: String = ""
var strict: bool = false
var list_all: bool = false


func _initialize() -> void:
	for a in OS.get_cmdline_user_args():
		if a.begins_with("--md="):
			md_out = a.substr(5)
		elif a.begins_with("--json="):
			json_out = a.substr(7)
		elif a == "--strict":
			strict = true
		elif a == "--list":
			list_all = true
	AnimData.load_waves = true
	_run.call_deferred()


func _run() -> void:
	AnimRig.setup()
	AnimData.load_all()
	var r: Dictionary = AnimHeldLint.scan()
	var scope_ok: bool = r.ok
	var ids: Array = r.ids
	var held: Dictionary = r.held_map
	var classes: Dictionary = r.classes
	var fails: Array = r.fails
	var nums: Array = r.numbers
	print("held-pose lint (h01 to h03, h05 and f01; scope RL-087%s): %d poses held 12 ticks or more %s, %d fail" % ["" if scope_ok else ", the scope was NOT found in docs/legal/movegen-banned.json", ids.size(), classes, fails.size()])
	for f in fails:
		print("  %-34s [%s] %s   [%s]" % [f.pose, f.class, "; ".join(f.why), "; ".join((f.sources as Array).slice(0, 2))])
	for n in nums:
		print("  number: ", n)
	if list_all:
		for pid in ids:
			print("  held: %s [%s] %s" % [pid, AnimHeldLint._class_of(pid), held[pid].sources])
	if json_out != "":
		var jf := FileAccess.open(json_out, FileAccess.WRITE)
		jf.store_string(JSON.stringify({"tool": "held_scan", "held": ids.size(), "classes": classes, "fails": fails, "numbers": nums}))
		jf.close()
	if md_out != "":
		var lines: PackedStringArray = ["# Held-pose lint: Legal's h01 to h03, scoped (RL-087)", "", "Generated by `render/anim/tools/held_scan.gd` from the scope in `docs/legal/movegen-banned.json` (`held`, `heldScope`). %d poses are held 12 ticks or more (classes: %s); **%d fail**." % [ids.size(), JSON.stringify(classes), fails.size()], "",
			"Tests: the pair test on every held pose (both hands within %.0f and both in the hip zone: x %.0f or less, height 24 to 44; or both wrists forward and within %.0f; a named brushing gesture is exempt); the emitter test on charge, tell, signature, energy and hold poses (the emitting hand open or clawed in the hip zone with its wrist at x %.0f or less, or any hand above %.0f); h02 (both elbows within %.0f degrees of straight and both hands %.0f or more out, outside On the Chin); h03 (a crouch with both fists at the sides in a tell)." % [AnimHeldLint.PAIR_APART, AnimHeldLint.HIP_X, AnimHeldLint.PAIR_WRISTS, AnimHeldLint.EMIT_WRIST_X, AnimHeldLint.HAND_TOP, AnimHeldLint.ARM_STRAIGHT, AnimHeldLint.ARM_WIDE], ""]
		if fails.is_empty():
			lines.append("**No pose fails.**")
			lines.append("")
		else:
			lines.append_array(["| Pose | Class | Held (ticks) | What fails | Where it is held |", "| :--- | :--- | ---: | :--- | :--- |"])
			for f in fails:
				lines.append("| `%s` | %s | %s | %s | %s |" % [f.pose, f.class, ("to the event" if float(f.ticks) >= 999.0 else "%.0f" % float(f.ticks)), "; ".join(f.why), "; ".join((f.sources as Array).slice(0, 3))])
			lines.append("")
		lines.append("## The numbers Legal asked for")
		lines.append("")
		for n in nums:
			lines.append("- " + String(n))
		var mf := FileAccess.open(md_out, FileAccess.WRITE)
		mf.store_string("\n".join(lines) + "\n")
		mf.close()
	quit(1 if (strict and (not fails.is_empty() or not scope_ok)) else 0)
