// Combat's eight rules for a medium thrown on Y's 12-tick wind-up (docs/combat/pending/movegen/parts.json `strike.windup`, review-sheet.md) as data/anim/medium_wind.json: which of the 16 martial
// mediums of each fighter follows which rule (read off the moveset rows: keys.set and wind), and what each rule does to the body. The rules' numbers are Animation's, written here.
//   node render/anim/tools/medium_wind_gen.mjs
// w1 a leap, w2 a spin, w3 two arms: held-Y only (they never play on 12 ticks), so they carry no change. w4 a dropping kick: the leg falls from hip height, not the full swing overhead (the chamber is cut to
// 0.55). w5 a dropping hand or elbow: no raise of its own, the arm starts at shoulder height (the chambers are drawn there; no cut). w6 a line: a half step, the body leans and does not travel (the step
// is halved). w7 an arc: the chamber is cut to a third, a flatter tighter arc. w8 a rise: no dip first (the chamber is cut to a quarter).
import { readFileSync, writeFileSync } from 'node:fs';
const root = new URL('../../../', import.meta.url);
const read = p => JSON.parse(readFileSync(new URL(p, root), 'utf8'));
const rules = {
  w4: { u_cap: 0.55, why: 'the knee lifts on the press and the leg falls from hip height: a chop of the leg, not the full swing overhead' },
  w5: { why: 'no raise of its own: the arm starts at shoulder height, where the guard or the last blow left it, and the body drops under it (the chambers of these strikes are drawn at shoulder height)' },
  w6: { step: 0.5, why: 'the step in is a half step: the body leans into the blow and does not travel' },
  w7: { u_cap: 0.34, why: 'the hips start to turn on the press and the chamber is cut to a third: a flatter, tighter arc' },
  w8: { u_cap: 0.25, why: 'no dip first: he rises from where he is. It no longer lifts by itself: the lift is the pair X+Y' },
};
const sets = {};
const held = [];
for (const who of ['rival', 'protagonist']) {
  const m = read(`docs/combat/pending/movegen/moveset.${who}.json`);
  const walk = o => {
    if (Array.isArray(o)) return o.forEach(walk);
    if (!o || typeof o !== 'object') return;
    if (typeof o.id === 'string' && o.id.startsWith(`mv.${who}.martial.y.`) && o.wind && o.keys && o.keys.set) {
      if (['w1', 'w2', 'w3'].includes(o.wind)) held.push(o.keys.set);
      else sets[o.keys.set] = o.wind;
    }
    Object.values(o).forEach(walk);
  };
  walk(m);
}
const out = {
  schema: 'anim.mediumwind/1',
  _about: "Combat's eight rules for a medium thrown on Y's 12-tick wind-up (docs/combat/pending/movegen/parts.json strike.windup), as the body does them (docs/animation/super-heavy.md). Render only, outside the sim's data hash. Generated by render/anim/tools/medium_wind_gen.mjs. rules: per rule, `u_cap` (the chamber is reached this far at most, 0 to 1: a flatter wind-up) and `step` (the share of the key set's step the body takes). sets: key set id to its rule, read only when a blow plays on the `medium` press style with a wind-up of 14 ticks or fewer. held_only: the key sets whose rule is w1 to w3, which only play on a held Y (the long wind-up), so they have no change here. Provisional with the press styles it belongs to: nothing in a live match names the style until the sim does (C2a).",
  rules,
  sets: Object.fromEntries(Object.entries(sets).sort(([a], [b]) => a.localeCompare(b))),
  held_only: [...new Set(held)].sort(),
};
writeFileSync(new URL('data/anim/medium_wind.json', root), JSON.stringify(out, null, 1).replace(/\[\n\s+([^\[\]{}]*?)\n\s+\]/g, (m, inner) => '[' + inner.replace(/\n\s+/g, ' ') + ']') + '\n');
console.log(`[medium_wind_gen] ${Object.keys(sets).length} mediums on a rule, ${out.held_only.length} held-only`);
