// The review pipeline (docs/animation/review-plan.md): machines do the first pass, Orb sees one reel, one exceptions sheet and a few
// A/B pairs per wave. No dependencies (Node 24 built-ins). Run from the repo root.
//
//   node render/anim/tools/review.mjs wave --name strikes [--ids strike.] [--seeds 4,12345] [--ticks 3000] [--no-match] [--project DIR]
//       Runs pose_lint, silhouette_lint, stacking_lint and (unless --no-match) limb_scan, joint_scan, pop_scan and anim_check, merges their findings
//       into art/animation/review/<name>/: exceptions.md (what Orb sees, with a reason and a suggested action for each), summary.json
//       (every finding, machine readable) and exceptions-sheet.png (a contact sheet of the flagged poses).
//   node render/anim/tools/review.mjs reel --name strikes --seed 4 --from 1800 --count 400 [--step 3] [--crop 260x150] [--args "--style=fluid"]
//       The wave's reel: a real seeded match window, before the overhaul on the left (--noragdoll) and after on the right, as a GIF.
//   node render/anim/tools/review.mjs ab --name strikes --a "--style=snappy" --b "--style=fluid" --seed 4 --from 735 --count 120
//       An A/B pair: the same window under two argument sets, side by side, to be answered by a letter.
//   node render/anim/tools/review.mjs pack --wave wave1 [--out DIR] [--project DIR]
//       A rich-moveset wave (render/anim/tools/waves/wave1.mjs, generated by wave_gen.mjs into data/anim/waves/): everything above for the
//       wave's poses (--waves is passed to every tool), plus Legal's lines (pose_lint `_legal`), the strike lab's reach and clip
//       measurements at each strike's own distance, a captioned reel of every strike against a dummy defender, a contact-frame
//       sheet, and an A/B GIF for each strike that has a B version. The pack is art/animation/review/<wave>/ and README.md says what is in it.
//   node render/anim/tools/review.mjs fix-reach --name strikes
//       Rewrites the hand and foot targets of the unreachable findings (not the strike poses, whose reach the contact slice reads) to
//       where the limb actually ends up: no visual change, the baked pose is what it was, but the data now says what the pose shows.
//
// GODOT_BIN names the Godot console executable (default: the one in %LOCALAPPDATA%\Programs\Godot\4.7.2). --project is the project
// directory to run in (default the current directory): use a clean export of HEAD plus your files when the working tree is busy.
import { spawnSync } from 'node:child_process';
import { existsSync, mkdirSync, readFileSync, writeFileSync, rmSync } from 'node:fs';
import { join, resolve } from 'node:path';

const argv = process.argv.slice(2);
const cmd = argv[0];
const opt = (n, d) => { const i = argv.indexOf('--' + n); return i >= 0 && i + 1 < argv.length && !argv[i + 1].startsWith('--') ? argv[i + 1] : d; };
const flag = n => argv.includes('--' + n);
const project = resolve(opt('project', '.'));
const waveName = opt('wave', '');
const name = opt('name', waveName || 'wave');
const wprefix = waveName ? (waveName === 'agency1' ? 'ag' : waveName === 'energy1' ? 'en' : waveName === 'protag1' ? 'pr' : waveName === 'protag2' ? 'pe' : waveName === 'protag3' ? 'pn' : waveName === 'protag4' ? 'pf' : waveName === 'rival1' ? 'rv' : waveName === 'rival2' ? 'rb' : waveName === 'rival3' ? 'rw' : waveName === 'protag5' ? 'pg' : waveName === 'pair1' ? 'pp' : waveName === 'protag6' ? 'ph' : waveName === 'protag10' ? 'pu' : waveName === 'rival7' ? 'ru' : waveName === 'protag9' ? 'pi' : waveName === 'rival6' ? 'ri' : waveName === 'pair2' ? 'zp' : waveName === 'protag7' ? 'pm' : waveName === 'protag8' ? 'ps' : waveName === 'rival4' ? 'rm' : waveName === 'rival5' ? 'rs' : waveName.startsWith('step') ? 's' + waveName.slice(4) : waveName.replace('wave', 'w')) + '.' : '';
const waveArgs = waveName ? ['--waves'] : [];
const godot = process.env.GODOT_BIN || join(process.env.LOCALAPPDATA || '', 'Programs/Godot/4.7.2/Godot_v4.7.2-stable_win64_console.exe');
const outRoot = resolve(opt('out', 'art/animation/review'));
const outDir = join(outRoot, name);
const rawDir = join(outDir, 'raw');
mkdirSync(rawDir, { recursive: true });

function runGodot(script, args, { headless = true, timeout = 900 } = {}) {
  const a = ['--path', project];
  a.push(headless ? '--headless' : '--no-window');   // never a window: the render tools draw offscreen
  a.push('--script', `res://render/anim/tools/${script}.gd`, '--', ...waveArgs, ...args);
  const r = spawnSync(godot, a, { encoding: 'utf8', timeout: timeout * 1000, maxBuffer: 1 << 28 });
  if (r.status !== 0 && r.status !== null && r.stdout.indexOf('passed') < 0 && r.stdout.indexOf('FAILED') < 0) console.error(`[review] ${script} exited ${r.status}`);
  return r.stdout || '';
}
const readManifest = () => { const c = join(project, `data/anim/waves/${waveName}.seqmap.json`); if (existsSync(c)) return readJson(c); const a = join(project, `data/anim/waves/${waveName}.entrymap.json`); const b = join(project, `data/anim/waves/${waveName}.manifest.json`); return readJson(existsSync(a) ? a : b); };
const readJson = p => existsSync(p) ? JSON.parse(readFileSync(p, 'utf8')) : null;

function wave() {
  const ids = opt('ids', wprefix);
  const seeds = opt('seeds', '4,12345');
  const ticks = opt('ticks', '3000');
  const idArgs = ids ? [`--ids=${ids}`] : [];
  const manifest = waveName ? readManifest() : null;
  const isEntries = manifest?.kind === 'entries';
  const isSeq = manifest?.kind === 'sequences';
  const found = [];
  const add = (severity, source, subject, detail, action) => found.push({ severity, source, subject, detail, action });
  // pose lint
  runGodot('pose_lint', [...idArgs, `--json=${join(rawDir, 'pose_lint.json')}`]);
  const pl = readJson(join(rawDir, 'pose_lint.json'));
  for (const it of pl?.issues ?? []) {
    if (it.kind === 'nan') add('error', 'pose_lint', it.id, it.detail, 'fix the pose data');
    else if (it.kind === 'legal') add('error', 'legal', it.id, it.detail, "Legal's line for this strike (docs/legal/rule-of-cool-screen.md): change the pose");
    else if (it.kind === 'unreachable') add(it.value > 5 ? 'review' : 'note', 'pose_lint', it.id, it.detail, it.value > 5 ? 'shorten the target or accept the clamped end (`fix-reach`)' : 'accept the clamped end (`fix-reach`)');
    else if (it.kind === 'joint range') add(it.value < -10 ? 'review' : 'note', 'pose_lint', it.id, it.detail, it.value < -10 ? 'a joint bent backwards: fix the pose' : 'the runtime limb pass trims the fold to 150 degrees, so the pose shows less than authored; relax it if the full fold is meant');
    else add('review', 'pose_lint', it.id, `${it.kind}: ${it.detail}`, 'adjust the pose');
  }
  // silhouette lint (the review threshold is a little under the lint's own)
  runGodot('silhouette_lint', [...idArgs, ...(waveName && !isSeq ? ['--suffix=' + (isEntries ? '.travel' : '.contact')] : []), '--cross=0.80', '--same=0.92', `--json=${join(rawDir, 'silhouette.json')}`]);
  const sl = readJson(join(rawDir, 'silhouette.json'));
  const fromOf = id => isEntries ? null : manifest?.strikes?.find(m => id.startsWith(m.id + '.') || id.startsWith(m.id + '~'))?.from ?? null;
  for (const pr of sl?.pairs ?? []) if (waveName && fromOf(pr.a) && fromOf(pr.a) === fromOf(pr.b)) add('note', 'silhouette_lint', `${pr.a} / ${pr.b}`, `overlap ${pr.iou}: two strikes derived from the same family (they differ by the hands or the target)`, 'by design (Combat\'s derive rows); the hands and the target tell them apart');
  for (const pr of (sl?.pairs ?? []).filter(p => !(waveName && fromOf(p.a) && fromOf(p.a) === fromOf(p.b)))) add(!isSeq && pr.iou >= (pr.kind === 'same family' ? 0.95 : 0.85) ? 'review' : 'note', 'silhouette_lint', `${pr.a} / ${pr.b}`, `overlap ${pr.iou} (${pr.kind})`, pr.kind === 'same family' ? 'a key that barely moves: make the poses differ or drop one' : 'two moves that read alike: change one silhouette (or add the pair to data/anim/lint_allow.json with a reason)');
  // stacking lint
  runGodot('stacking_lint', [`--json=${join(rawDir, 'stacking.json')}`]);
  const st = readJson(join(rawDir, 'stacking.json'));
  for (const m of st?.moments ?? []) {
    if (m.status === 'FAIL') add('error', 'stacking_lint', m.id, `${m.count} marks (${m.marks.join(', ')}), the cap is 2`, 'drop a mark: Legal\'s stacking rule (rule-of-cool section 1 rule 9)');
    else if (m.status === 'warn') add('review', 'stacking_lint', m.id, `2 marks (${m.marks.join(', ')}): no room left`, 'nothing else may be added to this moment');
  }
  for (const id of st?.mark_one_poses ?? []) add('note', 'stacking_lint', id, 'mark 1: a crouch with fists at the sides', 'fine alone; never in a moment that also has a scream, a flame aura, rising rubble, lightning, hair or a gold flash');
  // the strike lab: reach and clipping at each strike's own distance (waves only)
  let labNote = '';
  if (isEntries && !flag('no-lab')) {
    // how each entry flows into the strikes it favours: the mean turn of the eight limb bones from its last pose to the strike's wind-up
    runGodot('entry_lab', ['--measure', `--wave=${waveName}`, `--json=${join(rawDir, 'flow.json')}`]);
    const fj = readJson(join(rawDir, 'flow.json'));
    for (const r of fj?.flows ?? []) {
      const bad = r.flows.filter(f => f.mean > 1.6);
      if (bad.length) add('review', 'entry_lab', r.name, `the arrival is far from the wind-up of ${bad.map(f => f.strike + ' (' + f.mean + ' rad)').join(', ')}`, 'an arrival pose closer to those wind-ups, or let the join (inertialised) carry it');
      const mid = r.flows.filter(f => f.mean > 1.3 && f.mean <= 1.6);
      if (mid.length) add('note', 'entry_lab', r.name, `a long join into ${mid.map(f => f.strike + ' (' + f.mean + ' rad)').join(', ')}`, 'none needed unless the reel shows a jump');
    }
    labNote = `${fj?.flows?.length ?? 0} entries measured against the strikes they favour (the mean limb turn from the arrival to the wind-up)`;
  }
  if (waveName && !isEntries && !isSeq && !flag('no-lab')) {
    runGodot('strike_lab', ['--measure', `--wave=${waveName}`, `--json=${join(rawDir, 'reach.json')}`]);
    const rj = readJson(join(rawDir, 'reach.json'));
    for (const r of rj?.strikes ?? []) {
      if (r.gap > 1.0) add('review', 'strike_lab', r.name, `the limb ends ${r.gap} u short of the defender at ${r.dist} u (step-in ${r.step_in})`, "a pose that lets the limb reach (higher or longer), or a shorter contact distance in Combat's row");
      if (r.gap2 > 1.0) add('review', 'strike_lab', r.name, `the second limb ends ${r.gap2} u short at ${r.dist} u`, 'a pose that gives both limbs the reach, or a shorter contact distance');
      if (r.clip > 6.0) add('review', 'strike_lab', r.name, `a part that is not the striking limb passes ${r.clip} u into the defender (${r.clip_pair}) at ${r.dist} u`, 'pull the body back in the pose (less lunge or lean) or lengthen the distance');
      else if (r.clip > 3.5) add('note', 'strike_lab', r.name, `a part that is not the striking limb touches the defender by ${r.clip} u (${r.clip_pair}) at ${r.dist} u`, 'none needed unless it reads as a clip in the reel');
    }
    const n = rj?.strikes?.length ?? 0;
    labNote = `${n} strikes measured at their own distances: ${rj ? rj.strikes.filter(r => r.gap <= 1.0 && (r.gap2 ?? 0) <= 1.0).length : 0} reach, ${rj ? rj.strikes.filter(r => r.clip <= 3.5).length : 0} clear of the defender (clip 3.5 u or less)`;
  }
  // match-level checks
  let matchNote = 'not run (--no-match)';
  if (!flag('no-match') && !waveName) {
    runGodot('limb_scan', [`--seeds=${seeds}`, `--ticks=${ticks}`, `--json=${join(rawDir, 'limb_scan.json')}`]);
    const ls = readJson(join(rawDir, 'limb_scan.json'));
    for (const [k, v] of Object.entries(ls?.counts ?? {})) add('error', 'limb_scan', k, `${v} frames over ${ls.frames} fighter-frames`, 'a limb left human range in play: find the layer that did it');
    // the joint limits (data/anim/joints.json): no pose, sequence frame or live frame may be past a limit or bent the wrong way
    runGodot('joint_scan', [`--seeds=${seeds}`, `--ticks=${ticks}`, `--json=${join(rawDir, 'joint_scan.json')}`]);
    const js = readJson(join(rawDir, 'joint_scan.json'));
    if (js && js.bad > 0) {
      const sum = (g, k) => Object.values(g ?? {}).reduce((n, r) => n + (r[k] ?? 0), 0);
      add('error', 'joint_scan', 'joint limits', `${sum(js.report.poses, 'bad_frames')} pose frames, ${sum(js.report.sequences, 'bad_frames')} sequence frames and ${js.report.live_output?.bad_frames ?? 0} live frames are past a limit or bent the wrong way`, 'raw/joint_scan.json names each; docs/animation/joint-limits.md says what each rule is');
    }
    else if (js) add('note', 'joint_scan', 'joint limits', `0 past a limit in ${js.report.live_frames} live fighter-frames, every pose and every sequence frame (the sources alone leave ${js.report.live_stages?.D?.bad_frames ?? 0} live frames for the solve's last pass)`, 'none');
    runGodot('pop_scan', [`--seeds=${seeds}`, `--ticks=${ticks}`, `--json=${join(rawDir, 'pop_scan.json')}`]);
    const ps = readJson(join(rawDir, 'pop_scan.json'));
    // A join above the limit is an eased swing, not a jump (inertialisation, pose-pipeline 9.x); only a turn past 3 rad (more than
    // half a turn in six ticks) is something to look at, the rest are logged with their worst case.
    if (ps && ps.worst > 3.0) add('review', 'pop_scan', 'joins', `the worst join turns a bone ${ps.worst.toFixed(2)} rad in one tick (${ps.joins} joins over ${ps.limit} rad)`, 'a pose pops: look at the example ticks in raw/pop_scan.json');
    else if (ps && ps.joins > 0) add('note', 'pop_scan', 'joins', `${ps.joins} eased swings over ${ps.limit} rad in ${ps.frames} fighter-frames, worst ${ps.worst.toFixed(2)} rad (${(ps.examples?.[0]?.text ?? '').replace(/^seed \d+ tick \d+ /, '')})`, 'none: the offset settles on its curve; raw/pop_scan.json lists the worst ticks');
    runGodot('anim_check', [`--seeds=${seeds}`, `--ticks=${ticks}`, `--report=${join(rawDir, 'anim_check.json')}`]);
    const ac = readJson(join(rawDir, 'anim_check.json'));
    for (const f of ac?.failures ?? []) add('error', 'anim_check', 'check', String(f), 'fix before anything else');
    for (const r of ac?.runs ?? []) {
      if (r.contact_err_max > 0.02) add('error', 'anim_check', `contact error (${r.seed}, ${r.mode})`, `${r.contact_err_max.toFixed(4)} rad on a contact frame`, 'a blow no longer lands on its contact key');
      if (r.contact_gap_worst > 1.0) add('review', 'anim_check', `contact gap (${r.seed}, ${r.mode})`, `${r.contact_gap_worst.toFixed(2)} units short of the defender`, 'the reach (arm, lunge, step-in) is not enough for this strike');
      if (r.contacts_beyond_reach > 0 && r.mode === 'mix') add('note', 'anim_check', `blows beyond reach (${r.seed})`, `${r.contacts_beyond_reach} of ${r.contacts_beyond_reach + r.contacts_within_reach}`, 'the sim lands blows farther than the animator can reach (Combat/Encounter spacing)');
    }
    matchNote = `${seeds} for ${ticks} ticks: limb_scan ${ls ? 'clean' : 'no data'}, joint_scan ${js ? (js.bad ? js.bad + ' past a limit' : 'clean') : 'no data'}, anim_check ${ac ? (ac.failures.length ? ac.failures.length + ' failed' : 'passed, ' + ac.checks + ' checks') : 'no data'}`;
  }
  // the sheet of flagged poses
  const rank = { error: 0, review: 1, note: 2 };
  found.sort((a, b) => rank[a.severity] - rank[b.severity]);
  const flagged = [];
  for (const f of found) if (f.severity !== 'note') for (const part of f.subject.split(' / ')) if (/^[a-z][a-z0-9_~]*(\.[a-z0-9_~]+)*$/.test(part) && !flagged.includes(part) && flagged.length < 24) flagged.push(part);
  if (waveName) for (let i = 0; i < flagged.length; i++) { const m = manifest?.strikes?.find(x => x.name === flagged[i]); if (m) flagged[i] = m.id + '.contact'; const e = manifest?.entries?.find(x => x.name === flagged[i]); if (e) flagged[i] = e.poses[e.poses.length - 1]; }
  let sheet = '';
  if (flagged.length && !flag('no-sheet')) {
    sheet = join(outDir, 'exceptions-sheet.png');
    runGodot('pose_sheet', [`--out=${sheet}`, `--ids=${flagged.join(',')}`, '--cols=6', '--cell=190'], { headless: false, timeout: 300 });
  }
  // the markdown Orb reads
  const counts = { error: 0, review: 0, note: 0 };
  for (const f of found) counts[f.severity]++;
  const poseCount = pl?.poses ?? 0;
  const lines = [];
  lines.push(`# Review: ${name}`, '');
  lines.push(`Machine pass over ${poseCount} poses${ids ? ' (' + ids + ')' : ''}: **${counts.error} errors, ${counts.review} for review, ${counts.note} notes.** Errors are fixed by the director before Orb sees anything; the rows under "For review" are what Orb sees (with the sheet); notes are logged and need nobody.`, '');
  lines.push(`Match checks: ${matchNote}.${labNote ? ' Strike lab: ' + labNote + '.' : ''}`, '');
  if (sheet) lines.push(`Sheet of the flagged poses: ${'exceptions-sheet.png'}`, '');
  for (const [sev, title] of [['error', 'Errors (the director fixes these first)'], ['review', 'For review (what Orb sees)'], ['note', 'Notes (logged, no action needed)']]) {
    const rows = found.filter(f => f.severity === sev);
    if (!rows.length) continue;
    lines.push(`## ${title}`, '', '| Source | Subject | Finding | Suggested action |', '| :--- | :--- | :--- | :--- |');
    for (const r of rows.slice(0, sev === 'note' ? 40 : 200)) lines.push(`| ${r.source} | ${r.subject} | ${r.detail} | ${r.action} |`);
    if (rows.length > 40 && sev === 'note') lines.push(`| | | ... and ${rows.length - 40} more notes (summary.json) | |`);
    lines.push('');
  }
  writeFileSync(join(outDir, 'exceptions.md'), lines.join('\n'));
  writeFileSync(join(outDir, 'summary.json'), JSON.stringify({ wave: name, poses: poseCount, counts, flagged, findings: found }, null, 1));
  console.log(`[review] ${name}: ${poseCount} poses, ${counts.error} errors, ${counts.review} for review, ${counts.note} notes -> ${outDir}`);
}

function reel(extraA = [], extraB = [], labelA = 'noragdoll', labelB = '', gifName = null) {
  const seed = opt('seed', '4');
  const from = opt('from', '735');
  const count = opt('count', '120');
  const step = opt('step', '2');
  const crop = opt('crop', '220x140');
  const scale = opt('scale', '2');
  const mk = (tag, extra) => {
    const out = join(rawDir, `reel_${tag}.rgb`);
    runGodot('anim_reel', [`--out=${out}`, `--seed=${seed}`, `--from=${from}`, `--count=${count}`, `--step=${step}`, `--crop=${crop}`, `--scale=${scale}`, ...extra], { headless: false, timeout: 1800 });
    return out;
  };
  const a = mk('a', extraA);
  const b = mk('b', extraB);
  const gif = gifName || join(outDir, `${name}-reel.gif`);
  const r = spawnSync(process.execPath, [join(project, 'render/anim/tools/gif.mjs'), gif, a, b, '--delay', opt('delay', '5')], { encoding: 'utf8' });
  console.log(r.stdout.trim());
}

function pack() {
  if (!waveName) { console.error('pack needs --wave waveN'); process.exit(2); }
  wave();
  const man = readManifest();
  if (man?.kind === 'entries') { packEntries(man); return; }
  if (man?.kind === 'sequences') { packSeq(man); return; }
  const dir = outDir;
  // the reach table: the distance each strike reaches at, measured by the lab against Combat's own contact distance
  runGodot('strike_lab', ['--measure', '--sweep', `--wave=${waveName}`, `--json=${join(rawDir, 'sweep.json')}`]);
  const sw = readJson(join(rawDir, 'sweep.json'));
  const tl = ['# ' + waveName + ': the reach table', '',
    "Measured by `strike_lab.gd --measure --sweep`: each strike played against a dummy defender at every distance from 20 to 98 u. **Hips alone** is the farthest distance the blow lands at with the pose's own lunge and no step-in; **with step-in** adds the contact solve's whole-body slide (the limb's `step_max` or the key set's). **Clear from** is the nearest distance at which no other part of the body passes more than 6 u into the defender. Combat's rule (docs/combat/pending/wave1-strikes.md section 3) is that a strike's contact distance is its reach minus the step, so the blow lands with the hip lunge alone: the verdict column checks it.", '',
    '| Strike | Combat contact | Combat reach | Hips alone | With step-in | Clear from | Verdict |', '| :--- | ---: | ---: | ---: | ---: | ---: | :--- |'];
  for (const r of sw?.sweep ?? []) {
    const need = r.reach_hip >= r.combat_offset ? 0 : Math.max(0, r.combat_offset - r.reach_hip);
    const verdict = r.clear_from > r.combat_offset ? `too close: clips below ${r.clear_from} u` : (need === 0 ? 'lands on the hips alone' : `needs a step-in of ${need} u`);
    tl.push(`| ${r.name} | ${r.combat_offset} | ${r.combat_reach} | ${r.reach_hip} | ${r.reach_max} | ${r.clear_from} | ${verdict} |`);
  }
  writeFileSync(join(outDir, 'reach-table.md'), tl.join('\n') + '\n');
  // the reel of every strike and the contact sheet
  runGodot('strike_lab', [`--wave=${waveName}`, `--out=${join(rawDir, 'lab.rgb')}`], { headless: false, timeout: 1800 });
  const g = spawnSync(process.execPath, [join(project, 'render/anim/tools/gif.mjs'), join(dir, `${waveName}-reel.gif`), join(rawDir, 'lab.rgb'), '--delay', opt('delay', '4')], { encoding: 'utf8' });
  console.log(g.stdout.trim());
  runGodot('strike_lab', [`--wave=${waveName}`, `--sheet=${join(dir, `${waveName}-contact-sheet.png`)}`], { headless: false, timeout: 900 });
  // A/B pairs: a strike with a B version, side by side
  const pairs = [];
  for (const m of man?.strikes ?? []) {
    if (m._genericAb) pairs.push({ m, a: 'g', b: '', la: 'A: the generic wind-up of its limb', lb: 'B: its own family wind-up', note: `A is the generic wind-up of its limb, B its own family's (${m._family})` });
    if (m.alt) pairs.push({ m, a: '', b: 'b', la: 'A: as drawn', lb: 'B: ' + m.alt, note: `A is the strike as drawn; B is "${m.alt}"` });
  }
  const abs = [];
  for (const pr of pairs) {
    const nm = pr.m.name;
    const run = (v, label, f) => runGodot('strike_lab', [`--wave=${waveName}`, `--ids=${nm}`, ...(v ? [`--variant=${v}`] : []), `--label=${label}`, `--out=${join(rawDir, f)}`, '--step=2'], { headless: false, timeout: 300 });
    run(pr.a, pr.la, 'ab_a.rgb');
    run(pr.b, pr.lb, 'ab_b.rgb');
    const gf = join(dir, `ab-${nm}${pr.a === 'g' ? '-wind-up' : ''}.gif`);
    const r = spawnSync(process.execPath, [join(project, 'render/anim/tools/gif.mjs'), gf, join(rawDir, 'ab_a.rgb'), join(rawDir, 'ab_b.rgb'), '--delay', '5'], { encoding: 'utf8' });
    console.log(r.stdout.trim());
    abs.push({ file: `ab-${nm}${pr.a === 'g' ? '-wind-up' : ''}.gif`, note: pr.note });
  }
  const sum = readJson(join(dir, 'summary.json'));
  const c = sum?.counts ?? {};
  const poseTotal = sum?.poses ?? 0;
  const lines = [`# ${waveName}: the pack for Orb`, '',
    `Machine pass first (see exceptions.md): **${c.error ?? 0} errors, ${c.review ?? 0} for review, ${c.note ?? 0} notes** over ${poseTotal} poses of ${man?.strikes?.length ?? 0} strikes. Then what Orb sees:`, '',
    `1. **The reel** \`${waveName}-reel.gif\`: every strike, in order, against a dummy defender standing at the strike's own contact distance (the label gives the strike, the distance and its weight).`,
    `2. **The contact sheet** \`${waveName}-contact-sheet.png\`: the contact frame of every strike, one tile each, for a still look.`,
    '3. **The exceptions** `exceptions.md` and, when there are flagged poses, `exceptions-sheet.png`; and `reach-table.md`, the reach of every strike measured against the contact distances in the Combat rows.',
    `4. **${abs.length} A/B pairs**, each a choice between two versions of one strike, to be answered with a letter:`, '',
    ...abs.map(a => `   - \`${a.file}\`: ${a.note}.`), ''];
  writeFileSync(join(dir, 'README.md'), lines.join('\n'));
  for (const f of ['lab.rgb', 'ab_a.rgb', 'ab_b.rgb']) rmSync(join(rawDir, f), { force: true });   // the raw frames are 140 MB; the GIFs are the product
  console.log(`[review] pack ${waveName}: ${dir}`);
}

function packEntries(man) {
  const dir = outDir;
  const E = man.entries;
  // the flow table
  const fj = readJson(join(rawDir, 'flow.json'));
  const tl = [`# ${waveName}: the flow table`, '',
    "Each entry's last pose against the wind-up of every wave 1 strike it favours (Combat's `favours`): the mean turn of the eight limb bones in radians. Under 0.8 the join is nearly free, 0.8 to 1.3 it is a visible change the inertialisation smooths, over 1.3 the strike starts from a different shape (the pelvis and spine are the body's orientation, which the sim's rotation carries in flight, so only the limbs are compared).", '',
    '| Entry | Last pose | Strikes it favours (mean limb turn, rad) |', '| :--- | :--- | :--- |'];
  for (const r of fj?.flows ?? []) tl.push(`| ${r.name} | ${r.last} | ${r.flows.map(f => `${f.strike} ${f.mean}`).join(', ')} |`);
  writeFileSync(join(dir, 'flow-table.md'), tl.join('\n') + '\n');
  // the reel of every entry into its favoured strike, and the sheet (start, middle, arrival)
  runGodot('entry_lab', [`--wave=${waveName}`, `--out=${join(rawDir, 'lab.rgb')}`, '--size=420x260'], { headless: false, timeout: 1800 });
  const g = spawnSync(process.execPath, [join(project, 'render/anim/tools/gif.mjs'), join(dir, `${waveName}-reel.gif`), join(rawDir, 'lab.rgb'), '--delay', opt('delay', '4')], { encoding: 'utf8' });
  console.log(g.stdout.trim());
  runGodot('entry_lab', [`--wave=${waveName}`, `--sheet=${join(dir, `${waveName}-sheet.png`)}`, '--size=360x230'], { headless: false, timeout: 900 });
  const abs = [];
  for (const m of E.filter(x => x.alt)) {
    const run = (v, label, f) => runGodot('entry_lab', [`--wave=${waveName}`, `--ids=${m.name}`, ...(v ? [`--variant=${v}`] : []), `--label=${label}`, `--out=${join(rawDir, f)}`, '--step=2', '--size=360x230'], { headless: false, timeout: 300 });
    run('', 'A: as drawn', 'ab_a.rgb');
    run('b', 'B: ' + m.alt, 'ab_b.rgb');
    const file = `ab-${m.name}.gif`;
    const r = spawnSync(process.execPath, [join(project, 'render/anim/tools/gif.mjs'), join(dir, file), join(rawDir, 'ab_a.rgb'), join(rawDir, 'ab_b.rgb'), '--delay', '5'], { encoding: 'utf8' });
    console.log(r.stdout.trim());
    abs.push({ file, note: `A is the entry as drawn; B is "${m.alt}"` });
  }
  const sum = readJson(join(dir, 'summary.json'));
  const c = sum?.counts ?? {};
  const lines = [`# ${waveName}: the pack for Orb`, '',
    `Machine pass first (see exceptions.md): **${c.error ?? 0} errors, ${c.review ?? 0} for review, ${c.note ?? 0} notes** over ${sum?.poses ?? 0} poses of ${E.length} entries. Then what Orb sees:`, '',
    `1. **The reel** \`${waveName}-reel.gif\`: every entry, in order, played into the strike it favours, against a dummy defender. The lab moves him along a simple path (the sim owns the real one) and compresses the distance: a real rush covers 650 to 1,700 u, the reel shows 170.`,
    `2. **The sheet** \`${waveName}-sheet.png\`: three frames of each entry (the start, the middle, the arrival).`,
    '3. **The exceptions** `exceptions.md` and `exceptions-sheet.png`; and `flow-table.md`, how each arrival flows into the wind-ups of the strikes it favours.',
    `4. **${abs.length} A/B pairs**, each a choice between two versions of one entry, to be answered with a letter:`, '',
    ...abs.map(a => `   - \`${a.file}\`: ${a.note}.`), ''];
  writeFileSync(join(dir, 'README.md'), lines.join('\n'));
  for (const f of ['lab.rgb', 'ab_a.rgb', 'ab_b.rgb']) rmSync(join(rawDir, f), { force: true });
  console.log(`[review] pack ${waveName}: ${dir}`);
}

function packSeq(man) {
  const dir = outDir;
  // the timing table: each sequence's length against the sim number it answers
  const SIM = { perfect_block: 'riposteTicks 30 (the riposte window the defender holds loaded)', stagger_blocked: 'staggerTicks 24 (the blocked attacker)', reversal: 'the counter-delay beat, 8 ticks', stagger_countered: 'the delay and land of the reversal (about 16)', dodge_cancel: 'the dash out, about 10 ticks', burst: 'the burst, no sim length (the shove is the sim\'s)', shoved: 'the shove, about 12 ticks', stagger_bait: 'baitStaggerTicks 30 (the burster absorbed)', absorb: 'the burst absorbed, a brief brace' };
  const tl = [`# ${waveName}: timing`, '', "Each sequence is as long as the sim's own state it dresses (data/combat/templates.json, sim/director/interrupt.gd), so the pose never outlasts the game's stagger or riposte window.", '', '| Sequence | Ticks | Seconds | The sim number it answers |', '| :--- | ---: | ---: | :--- |'];
  for (const q of man.sequences) tl.push(`| ${q.name} | ${q.dur} | ${(q.dur / 60).toFixed(2)} | ${SIM[q.name] ?? ''} |`);
  writeFileSync(join(dir, 'timing.md'), tl.join('\n') + '\n');
  runGodot('cue_lab', [`--out=${join(rawDir, 'lab.rgb')}`, '--size=380x240'], { headless: false, timeout: 900 });
  const g = spawnSync(process.execPath, [join(project, 'render/anim/tools/gif.mjs'), join(dir, `${waveName}-reel.gif`), join(rawDir, 'lab.rgb'), '--delay', opt('delay', '4')], { encoding: 'utf8' });
  console.log(g.stdout.trim());
  runGodot('cue_lab', [`--sheet=${join(dir, `${waveName}-sheet.png`)}`, '--size=360x230'], { headless: false, timeout: 600 });
  const abs = [];
  const KINDS = { perfect_block: 'perfect_block', stagger_blocked: 'perfect_block', burst: 'burst' };
  for (const q of man.sequences.filter(x => x.alt)) {
    const cue = KINDS[q.name];
    if (!cue) continue;
    const run = (v, label, f) => runGodot('cue_lab', [`--cues=${cue}`, ...(v ? [`--variant=${v}`] : []), `--label=${label}`, `--out=${join(rawDir, f)}`, '--step=2', '--size=360x230'], { headless: false, timeout: 300 });
    run('', `A: ${q.name} as drawn`, 'ab_a.rgb');
    run('b', `B: ${q.alt}`, 'ab_b.rgb');
    const file = `ab-${q.name}.gif`;
    const r = spawnSync(process.execPath, [join(project, 'render/anim/tools/gif.mjs'), join(dir, file), join(rawDir, 'ab_a.rgb'), join(rawDir, 'ab_b.rgb'), '--delay', '5'], { encoding: 'utf8' });
    console.log(r.stdout.trim());
    abs.push({ file, note: `A is the ${q.name.replace('_', ' ')} as drawn; B is "${q.alt}"` });
  }
  const sum = readJson(join(dir, 'summary.json'));
  const c = sum?.counts ?? {};
  const lines = [`# ${waveName}: the pack for Orb`, '',
    `Machine pass first (see exceptions.md): **${c.error ?? 0} errors, ${c.review ?? 0} for review, ${c.note ?? 0} notes** over ${sum?.poses ?? 0} poses of ${man.sequences.length} sequences. Then what Orb sees:`, '',
    `1. **The reel** \`${waveName}-reel.gif\`: each of Encounter's step 3 cue events in turn (perfect block, reversal, dodge-cancel, burst, burst absorbed), sent through the real solver; the fighter who does it is on the right, the one it happens to on the left.`,
    `2. **The sheet** \`${waveName}-sheet.png\`: three frames of each.`,
    '3. **The exceptions** `exceptions.md` and `timing.md` (each sequence as long as the sim state it dresses).',
    `4. **${abs.length} A/B pairs**, each a choice between two versions, to be answered with a letter:`, '',
    ...abs.map(a => `   - \`${a.file}\`: ${a.note}.`), ''];
  writeFileSync(join(dir, 'README.md'), lines.join('\n'));
  for (const f of ['lab.rgb', 'ab_a.rgb', 'ab_b.rgb']) rmSync(join(rawDir, f), { force: true });
  console.log(`[review] pack ${waveName}: ${dir}`);
}

function fixReach() {
  const sum = readJson(join(outDir, 'raw/pose_lint.json'));
  if (!sum) { console.error('no raw/pose_lint.json: run the wave first'); process.exit(1); }
  const path = join(project, 'data/anim/poses.json');
  let txt = readFileSync(path, 'utf8');
  let n = 0;
  // strike poses keep their authored reach: the contact slice reads it
  for (const it of sum.issues.filter(i => i.kind === 'unreachable' && !i.id.startsWith('strike.'))) {
    const re = new RegExp(`("${it.id.replace(/\./g, '\\.')}": \\{[^\\n]*?"${it.limb}": )\\[[^\\]]*\\]`);
    if (re.test(txt)) { txt = txt.replace(re, `$1[${it.achieved.join(', ')}]`); n++; }
  }
  writeFileSync(path, txt);
  console.log(`[review] fix-reach: ${n} targets moved to where the limb ends up`);
}

if (cmd === 'wave') wave();
else if (cmd === 'reel') reel(['--noragdoll'], []);
else if (cmd === 'ab') reel((opt('a', '')).split(' ').filter(Boolean), (opt('b', '')).split(' ').filter(Boolean), 'A', 'B', join(outDir, `${name}-ab.gif`));
else if (cmd === 'fix-reach') fixReach();
else if (cmd === 'pack') pack();
else { console.error('usage: node render/anim/tools/review.mjs wave|reel|ab|pack|fix-reach --name NAME ...  (see the header of this file)'); process.exit(2); }
